# Backend/docker-compose.yml
services:
  db:
    image: mysql:8.0.37
    container_name: term-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      # Opcional: usuario app
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      # Puerto del HOST -> puerto interno MySQL
      - "${DB_HOST_PORT:-3307}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      # Opci√≥n CMD (no shell) usando variables de tu .env
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped

  datadog:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE:-us5.datadoghq.com}   # usa tu sitio
      DD_ENV: ${DD_ENV:-dev}
      DD_SERVICE: ${DD_SERVICE:-backend}
      DD_VERSION: ${DD_VERSION:-1.0.0}
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE_LOGS: "name:datadog-agent"
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
    ports:
      - "8125:8125/udp"   # DogStatsD
      - "8126:8126/tcp"   # APM
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    restart: unless-stopped

volumes:
  mysql_data:
