services:
  mysql:
    image: mysql:8.0.37
    container_name: term-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '7465726D696E61'
      MYSQL_DATABASE: 'term'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p7465726D696E61"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always

  datadog:
    image: datadog/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}  # ‚Üê variables, NO valores literales
      - DD_SITE=${DD_SITE}
      - DD_ENV=${NODE_ENV}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=false
    ports:
      - "8125:8125/udp"
      - "8126:8126/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    restart: always

volumes:
  mysql_data: